const SUPABASE_URL='https://qclqyqjxsnnhlnlhjybo.supabase.co';const SUPABASE_KEY='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFjbHF5cWp4c25uaGxubGhqeWJvIiwiaWF0IjoxNzQxMjMxNzQwLCJleHAiOjIwNTY3OTE3NDB9.K26768wVqF0L0L8y1k892wB5k8v80-001x';const db=supabase.createClient(SUPABASE_URL,SUPABASE_KEY);const $=s=>document.querySelector(s);const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
$('#hamb').onclick=()=>document.body.classList.toggle('nav-open');document.querySelectorAll('#nav a').forEach(a=>a.onclick=()=>document.body.classList.remove('nav-open'));
const fallbackIssues=Array.from({length:9},(_,i)=>({id:'fallback-'+(i+1),issue_number:i+1,title:'العدد '+(i+1),publication_date:'',pdf_url:'',cover_image:''}));const fallbackSections=['رؤى سينمائية','مراجعات','أفلام الشهر','بروفايل','مهرجانات','حوار العدد','الملف','متابعات'];
async function get(table,order='created_at',ascending=false){try{const r=await db.from(table).select('*').order(order,{ascending});return r.data||[]}catch(e){return[]}}
function cover(x,small=false){return x.cover_image?`<img src="${esc(x.cover_image)}" alt="غلاف العدد ${esc(x.issue_number)}">`:`<span>العدد ${esc(x.issue_number)}</span>`}
function renderIssues(items){$('#issuesGrid').innerHTML=items.map(x=>`<article class="issue-card"><div class="issue-cover">${cover(x,true)}</div><div class="issue-body"><strong>العدد ${esc(x.issue_number)}</strong><p>${esc(x.title||'ضد السينما !؟')} ${x.publication_date?'— '+esc(x.publication_date):''}</p><div class="issue-links">${x.pdf_url?`<a class="mini red" target="_blank" href="${esc(x.pdf_url)}">تصفح PDF</a>`:'<span class="mini">PDF قريباً</span>'}<a class="mini" href="#articles">المقالات</a></div></div></article>`).join('')}
function renderCurrent(x){if(!x){$('#currentIssue').innerHTML='<div class="empty">لم يتم اختيار عدد الشهر بعد. يمكنك تحديده من لوحة التحكم.</div>';return}$('#currentIssue').innerHTML=`<div class="current-cover">${x.cover_image?`<img src="${esc(x.cover_image)}" alt="غلاف العدد">`:`<div class="placeholder-cover">العدد ${esc(x.issue_number)}</div>`}</div><div class="current-info"><div class="num">العدد ${esc(x.issue_number)}</div><h3>${esc(x.title||'ضد السينما !؟')}</h3><p>${x.publication_date?esc(x.publication_date):'عدد جديد من المجلة المستقلة للنقد السينمائي.'}</p><p>تصفح العدد، واقرأ ملفاتنا ومراجعاتنا وحواراتنا السينمائية.</p>${x.pdf_url?`<a class="btn primary" target="_blank" href="${esc(x.pdf_url)}">تصفح وتحميل العدد PDF</a>`:''}</div>`}
function renderSections(items){const a=items.length?items:fallbackSections.map((name,i)=>({name,description:'قسم من أقسام المجلة',sort_order:i}));$('#sectionsGrid').innerHTML=a.map(x=>`<div class="section-card"><b>${esc(x.name)}</b><p>${esc(x.description||'كتابات ومتابعات نقدية حول السينما.')}</p></div>`).join('')}
function renderArticles(items){$('#articlesGrid').innerHTML=items.length?items.slice(0,9).map(x=>`<article class="article-card"><div class="cat">${esc(x.category||'نقد سينمائي')}</div><h3>${esc(x.title)}</h3><p>${esc(x.excerpt||'')}</p><small>${esc(x.author||'هيئة التحرير')}</small></article>`).join(''):'<div class="empty">ستظهر المقالات هنا فور إضافتها من لوحة التحكم.</div>'}
function renderTeam(items){$('#teamGrid').innerHTML=items.length?items.map(x=>`<article class="person"><div class="avatar">${x.image_url?`<img src="${esc(x.image_url)}" alt="">`:esc((x.name||'?').slice(0,1))}</div><h3>${esc(x.name)}</h3><div class="role">${esc(x.role||'')}</div><p>${esc(x.bio||'')}</p></article>`).join(''):'<div class="empty">أضف أعضاء هيئة التحرير من لوحة التحكم.</div>'}
async function main(){const [issues,sections,articles,team,settings]=await Promise.all([get('issues','issue_number',false),get('sections','sort_order',true),get('articles','created_at',false),get('team','sort_order',true),db.from('settings').select('*').eq('id',true).maybeSingle().then(r=>r.data||null).catch(()=>null)]);const all=issues.length?issues:fallbackIssues;renderIssues(all);renderSections(sections);renderArticles(articles);renderTeam(team);let current=settings?.current_issue_id?issues.find(x=>x.id===settings.current_issue_id):null;if(!current)current=issues[0]||null;renderCurrent(current);if(settings){if(settings.site_name)document.title=settings.site_name;if(settings.hero_title)$('#heroTitle').textContent=settings.hero_title;if(settings.hero_subtitle)$('#heroDesc').textContent=settings.hero_subtitle;if(settings.about_title)$('#aboutTitle').textContent=settings.about_title;if(settings.about_text)$('#aboutText').textContent=settings.about_text;if(settings.about_text_2)$('#aboutText2').textContent=settings.about_text_2;if(settings.contact_email){$('#contactEmail').href='mailto:'+settings.contact_email;$('#contactEmail').textContent=settings.contact_email}}}main();
